# Setup
title: Bloco de notas
url: https://sumitani.github.io
paginate: 3
baseurl: "https://sumitani.github.io"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-63888347-2

# Specify the author for blog posts
author:
  name: Rosemary Sumitani
  url: https://twitter.com/rose_sumitani

# Custom vars
version: 0.0.1

# Navbar page list
nav:
  - title: Blog
    url: /archive
